services:
  logosnext-site:
    container_name: logosnext-site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
