services:
  logosnext-site:
    container_name: logosnext-site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - nginx_net
networks:
  nginx_net:
    external: true